language: go

go:
  - 1.9

install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

before_script:
  - go vet
  - go build ./vendor/github.com/golang/lint/golint
  - ./golint -set_exit_status
